#pragma once
// AUTO GENERATED - DO NOT EDIT
// Generated from: txt.csv

typedef enum {
	TXT_EMPTY,
	TXT_PLAY,
	TXT_INSTRUCTIONS,
	TXT_SCORE,
	TXT_GAME_OVER,
	TXT_EXPERIENCE,
	TXT_LEVEL_UP,
	TXT_CHOOSE_UPGRADE,
	TXT_GAME_PAUSED,
	TXT_TRY_AGAIN,
	TXT_PRESS_TO_PLAY,
	TXT_GAME_TITLE,
	TXT_UPGRADE_DAMAGE,
	TXT_UPGRADE_FIRERATE,
	TXT_UPGRADE_MULTISHOT,
	TXT_LANGUAGE,
	TXT_GERMAN,
	TXT_ENGLISH,
	TXT_CHINESE,
	TXT_QUIT,
	TXT_CONTINUE,
	TXT_SETTINGS,
	TXT_COUNT
} TextID;

typedef enum {
	LANG_EN,
	LANG_DE,
	LANG_ZH,
	LANG_COUNT
} Language;

static const char *gText[LANG_COUNT][TXT_COUNT] = {
  {
	"",
	"Play",
	"WASD to move, space to shoot, p to pause",
	"Score: %d",
	"Game Over",
	"XP",
	"LEVEL UP!",
	"CHOOSE UPGRADE",
	"Game is paused...",
	"Press enter to try again",
	"Press enter to play",
	"Asteroids",
	"Increased Damage",
	"Increased Firerate",
	"+2 Projectiles",
	"Language:",
	"German",
	"English",
	"Chinese",
	"Quit",
	"Continue",
	"Settings",
  },
  {
	"",
	"Spielen",
	"WASD zum bewegen, leertaste zum schiessen, p zum pausieren",
	"Punktzahl: %d",
	"Game Over",
	"XP",
	"LEVEL UP!",
	"WÄHLE EIN UPGRADE",
	"Spiel ist pausiert...",
	"Drück enter um es erneut zu versuchen",
	"Drück enter um zu spielen",
	"Asteroids",
	"Erhöhter Schaden",
	"Erhöhte Feuerrate",
	"+2 Projektile",
	"Sprache:",
	"Deutsch",
	"Englisch",
	"Chinesisch",
	"Beenden",
	"Fortfahren",
	"Einstellungen",
  },
  {
	"",
	"玩",
	"WASD键移动, 空格键射击, P键暂停",
	"得分：%d ",
	"游戏结束 ",
	"XP",
	"升级！",
	"选择升级 ",
	"游戏暂停...",
	"按回车键重试 ",
	"按回车键即可播放 ",
	"小行星 ",
	"伤害增加",
	"射速增加",
	"+2 射弹",
	"语言：",
	"德语 ",
	"英语 ",
	"中文 ",
	"辞职 ",
	"继续 ",
	"设置",
  },
};
